TheDan64/inkwell

src/types/array_type.rs, src/types/float_type.rs, src/types/fn_type.rs, src/types/int_type.rs, src/types/mod.rs, src/types/ptr_type.rs, src/types/struct_type.rs, src/types/vec_type.rs, src/types/void_type.rs, src/values/array_value.rs, src/values/float_value.rs, src/values/fn_value.rs, src/values/instruction_value.rs, src/values/int_value.rs, src/values/metadata_value.rs, src/values/mod.rs, src/values/phi_value.rs, src/values/ptr_value.rs, src/values/struct_value.rs, src/values/vec_value.rs, tests/test_types.rs, tests/test_values.rs
Also added tests related to them. Fixes #14.
=> Added Copy + Clone traits to values & types

examples/kaleidoscope/main.rs, src/context.rs, src/lib.rs, src/module.rs, src/passes.rs, src/targets.rs, tests/test_builder.rs, tests/test_execution_engine.rs, tests/test_passes.rs, tests/test_targets.rs, tests/test_tari_example.rs
Modified some signatures for safety / readability, and added some doc comments.
=> Improvements to documentation

examples/kaleidoscope/main.rs, src/execution_engine.rs
It works on my machine (and some tests have been made related to it), so it should be good. I'll add `no_run` if Travis fails to build this.
=> Adding ExecutionEngine::add_global_mapping

README.md
Hello,
Thanks for the great project!
This patch fixes a small typo, and expand a link a little bit.
=> doc(readme) Fix a small typo

examples/kaleidoscope/main.rs
This fixes the ability of Kaleidoscope JIT to detect functions defined in Rust.
#74 
External functions have been tested in Kaleidoscope REPL:
```
?> extern printd(x)
?> printd(10)
10
=> 10
?> extern putchard(x)
?> putchard(33)
!=> 33
```
=> Fix detection of extern functions defined in Rust

src/basic_block.rs, tests/all/test_basic_block.rs
#93 
Tests pass
Slightly changes the api to return a Result
=> Add parent checking to BB methods. Fixes #93

src/attributes.rs, src/context.rs, src/data_layout.rs, src/memory_buffer.rs, src/module.rs, src/support/error_handling.rs, src/targets.rs, src/types/float_type.rs, src/types/int_type.rs, src/values/call_site_value.rs, src/values/fn_value.rs, src/values/mod.rs
error[E0308]: mismatched types
--> src/support/error_handling.rs:49:13
|
47 |     pub(crate) fn get_description(&self) -> *mut i8 {
|                                             ------- expected `*mut i8` because of return type
48 |         unsafe {
49 |             LLVMGetDiagInfoDescription(self.diagnostic_info)
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found u8
|
= note: expected type `*mut i8`
found type `*mut u8`
error[E0308]: mismatched types
--> src/attributes.rs:86:45
|
86 |             LLVMGetEnumAttributeKindForName(name.as_ptr() as *const i8, name.len())
|                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8
|
= note: expected type `*const u8`
found type `*const i8`
(etc)
Signed-off-by: Sean Young …
=> Cannot build on armv7 as c_char is unsigned

src/context.rs, src/values/vec_value.rs, tests/all/test_values.rs
=> Allow non utf8 string data in globals

src/builder.rs, tests/all/test_builder.rs
Now `build_memcpy` and `build_memmove` return an `Err` if given alignment values that will trigger LLVM's assertions.
Previously we leaned on LLVM module verification for that, but as of LLVM 10 there's an assertion which gets tripped prior to verification.
Fixes #168
Ran tests locally on llvm10, which was where the tests were failing in #168
=> Err for invalid memcpy/memmove alignmen

Cargo.toml
I believe this should have been missed in 9edf19a545a1ee80762d35abc0b113cc83ff807b.
=> Update `inkwell_internals` to 0.2

Cargo.toml, src/builder.rs, src/debug_info.rs, src/lib.rs, src/module.rs, src/values/fn_value.rs, tests/all/main.rs, tests/all/test_debug_info.rs
This is built off of epilys' PR #180. I've addressed the review feedback and added the extensions that I need for my use case.
#180 
I've used this to generate line table info but indeed there's no tests included yet.
=> Add support for debug info.

src/builder.rs, tests/all/test_builder.rs
now sure how both I and CI missed all this, but a bunch of tests had type errors...
=> fix invoke tests

Cargo.toml, internal_macros/src/lib.rs, src/context.rs, src/debug_info.rs, src/lib.rs, src/module.rs, src/types/enums.rs, src/values/metadata_value.rs, tests/all/test_builder.rs, tests/all/test_debug_info.rs, tests/all/test_passes.rs, tests/all/test_values.rs
support llvm 13
tests compile and all pass
The `create_inline_asm` function has an extra argument (`can_throw: bool`). Surprisingly, that's it!
=> Llvm 13 support

src/targets.rs
Oh, I made a very stupid copy & paste mistake in previous PR #294  .
I'm sorry to have to do twice.
#291
`cargo test --features llvm13-0`
=> Fix RISC-V Disassembler support

src/module.rs, tests/all/test_module.rs
Adds an iterator over the functions of a module. 
This is just an addition, no existing code is affected. The test suite passes, a doctest for this function has been added
=> add Module::get_functions and FunctionIterator

Cargo.toml, internal_macros/src/lib.rs, src/context.rs, src/debug_info.rs, src/lib.rs, src/module.rs, src/types/enums.rs, src/values/metadata_value.rs, tests/all/test_debug_info.rs, tests/all/test_passes.rs, tests/all/test_targets.rs, tests/all/test_values.rs
This is a WIP to support a new version of LLVM.
It's currently [blocked by `llvm-sys`](https://gitlab.com/taricorp/llvm-sys.rs/-/issues/30).
#316
This builds locally on my machine (I tested it both with v13 and v14). We'll need to wait until `llvm-sys-140` is released though.
=> Add support for LLVM 14

src/values/fn_value.rs, src/values/global_value.rs, tests/all/test_object_file.rs, tests/all/test_values.rs
Adds support for nullable sections & checks for null ptrs
Fixes #220 
Unit tests updated
Input/Output types changed to Options
=> Added support for and fixes null sections

examples/kaleidoscope/main.rs, src/attributes.rs, src/comdat.rs, src/context.rs, src/debug_info.rs, src/intrinsics.rs, src/support/mod.rs, src/targets.rs, src/values/call_site_value.rs, src/values/fn_value.rs, src/values/global_value.rs, src/values/instruction_value.rs, tests/all/test_instruction_values.rs, tests/all/test_targets.rs
Run `cargo clippy --fix --features llvm14-0`
Clippy fixed lot of unused imports, redundant returns, added usage of more specific functions, etc.
Tested for compilation
=> Clippy autofix

src/types/enums.rs, src/values/fn_value.rs, src/values/global_value.rs, src/values/mod.rs, tests/all/test_object_file.rs, tests/all/test_targets.rs
My bad, forgot to run fmt on some pull requests. Here are fixes
=> Apply fmt fixes

README.md
Update the Readme with llvm15 as an additional supported llvm version.
Added in #383 and support mentioned in #382
N/A
N/A
N/A
=> Update Readme with llvm15 feature flags

Cargo.toml, src/targets.rs
This PR aims to add support for LoongArch.
It depends on
```bash
cargo test --features llvm16-0
```
None
None
=> Add support for LoongArch

README.md
If I read the change log correctly, there is now llvm16 support.
#407
N/A
N/A
- [s] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)
=> Update README.md with llvm 16 support

src/lib.rs
Actually I lied, looks like there are a few more changes:
[`master...jamesmth:inkwell:llvm-plugin`#diff-b1a35a68f1](https://github.com/TheDan64/inkwell/compare/master...jamesmth:inkwell:llvm-plugin#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759)
=> Make llvm_sys a public export

src/types/mod.rs, src/types/struct_type.rs, src/values/instruction_value.rs, src/values/mod.rs, src/values/phi_value.rs, src/values/struct_value.rs, tests/all/test_instruction_values.rs, tests/all/test_types.rs, tests/all/test_values.rs
I think I got them all this time.
=> Add even more iterators

src/values/enums.rs, src/values/traits.rs
=> Add get_name to values

src/context.rs
Makes ContextRef copyable
#472 
`cargo t --features llvm17-0`
=> Make ContextRef copyable

tests/all/test_targets.rs
Fixes target test on arm64 machine
Same as #49, but on Apple Silicon
`cargo t --features llvm17-0` on `arm64-apple-darwin22.1.0`
=> Fix default target test
