TheDan64/inkwell

- src/lib.rs
- src/module.rs
- src/types/array_type.rs
- src/types/float_type.rs
- src/types/int_type.rs
- src/types/mod.rs
- src/types/ptr_type.rs
- src/types/struct_type.rs
- src/types/void_type.rs
- tests/test_builder.rs
- tests/test_types.rs
- tests/test_values.rs
Use `AddressSpace` instead of `u32` everywhere.
#24.
All existing tests have been run again.
Many methods can no longer be called with an integer, and now need an enum. The methods should be clearer and safer to use, although some calls may have to be changed.
> AddressSpace everywhere (fixes #24)

- src/basic_block.rs
- src/builder.rs
- src/data_layout.rs
- src/lib.rs
- src/memory_buffer.rs
- src/object_file.rs
- src/passes.rs
- src/types/fn_type.rs
- src/types/mod.rs
- src/values/array_value.rs
- src/values/fn_value.rs
- src/values/generic_value.rs
- src/values/metadata_value.rs
- src/values/mod.rs
Implements the `Debug` trait for all public-facing APIs. I also added a `#[deny(missing_debug_implementations)]` lint so non-`Debug` types can't accidentally sneak back in over time.
Fixes #7
It compiles.
> Impl debug

- .travis.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/module.rs
- src/passes.rs
- src/targets.rs
- src/values/metadata_value.rs
- tests/test_passes.rs
- tests/test_targets.rs
- tests/test_tari_example.rs
- tests/test_values.rs
* Added 4.0 test build to travis (3.9 has linking issues due to some travis-ubuntu issue, and may not be resolvable - will create an issue to do more research into it)
* Updated travis doc build to 4.0
* Added LLVM 3.9 & 4.0 support
Updates #1 to support LLVM 3.9 & 4.0
3.9 & 4.0 tests are passing. However, 3.9 is not being tested in travis due to a travis/ubuntu linking issue (should not affect most ubuntu users)
No breaking changes
> Support LLVM 3.9 + 4.0

- README.md
- examples/jit.rs
- examples/kaleidoscope/main.rs
- src/builder.rs
- src/types/mod.rs
- src/types/traits.rs
- src/values/mod.rs
- src/values/traits.rs
- tests/test_builder.rs
- tests/test_execution_engine.rs
- tests/test_tari_example.rs
- tests/test_values.rs
This PR introduces the ability for math functions to take and return vector values in a type-safe way, as discussed in #45. Please note that I'm pretty new to Rust in general, so there are possibly some things here that can be done better :)
The PR primarily introduces two new traits, `FloatMathValue` and `IntMathValue`, which are implemented by `FloatValue`/`VectorValue` and `IntValue`/`VectorValue` respectively. Applicable methods on the `Builder` have been adjusted to take and return a type that implements these traits - meaning, for example, if you call `build_float_add` with a vector as the LHS, you must pass a vector for the RHS and you will get a vector back. Since there's no sub-type support yet we can't ensure the passed vectors are actually composed of integers or floats, …
> Support vector types in math ops, fixes #45

- tests/test_module.rs
- tests/test_targets.rs
Add `terget_os="macos"` cases for tests (in place of #50 against master, and w/o rust-formating the files to minimize the diff). 
For the tests that were linux specific this adds cases to run on macos
https://github.com/TheDan64/inkwell/issues/49
The changes are exclusive to tests.
> Add macos cases for linux specific tests

- build.rs
I fixed a link error caused by the absence of ffi.lib so that I can use inkwell on Windows.
I have not tested it
> support windows OS

- src/values/global_value.rs
- tests/all/test_values.rs
Add ability to set linkage on GlobalValues.
Added basic tests as well, if you want some more tests, tell me and I will add them.
https://github.com/TheDan64/inkwell/issues/79
I believe this should be a very localized change. There are some very basic tests.
I have tested this with LLVM 7.0 only. I presume CI will run tests for everything else.
> Add ability to set linkage on GlobalValues

- src/memory_buffer.rs
One-line fix for #83
Fixes #83
The reproduction example in #83 throws an error without this patch, and does not throw an error after this patch has been applied (to the `llvm7-0` branch).  `cargo test` still passes on the `llvm7-0` branch after this patch has been applied.  I have not tested branches other than the `llvm7-0` branch, including `master` (although the patch applies cleanly), and have not tested on platforms other than macOS.
> bugfix: use CString when passing path across FFI

- src/values/array_value.rs
- src/values/enums.rs
- src/values/float_value.rs
- src/values/fn_value.rs
- src/values/global_value.rs
- src/values/instruction_value.rs
- src/values/int_value.rs
- src/values/metadata_value.rs
- src/values/mod.rs
- src/values/phi_value.rs
- src/values/ptr_value.rs
- src/values/struct_value.rs
- src/values/vec_value.rs
This is a very small PR, so I hope you don't mind I submitted it without making an issue first (although I can certainly go back and make an issue if you want).  This PR simply adds `#[derive(Hash)]` to `Value`, its subtypes (e.g. `IntValue`), and the value-related enums (e.g. `BasicValueEnum`).  The primary motivation is so that downstream users can use any of these types as keys in `HashMap`s.  No functionality should be affected.
I tested this on the `llvm7-0` branch and all tests still pass.
> Derive Hash on a bunch of Value types

- src/values/instruction_value.rs
- tests/all/test_instruction_values.rs
First shot at adding bindings for `LLVMGetICmpPredicate` and `LLVMGetFCmpPredicate`, functions in `llvm-sys` which currently aren't exposed.
Slightly unsure about the correct API here.  I have both of the bindings checking that the `InstructionValue` is indeed the correct operation (`ICmp` or `FCmp` respectively) before making the call to get the predicate; this will involve an extra unnecessary call into LLVM in the case where the caller does know that the opcode is correct.  A simpler binding would not perform this check (and therefore not have to return `Option` either).  I'm unsure what the behavior of LLVM is when calling, e.g., `LLVMGetICmpPredicate` on a non-`ICmp` instruction.
Fixes #86
New tests were added (well, ok, existing tests were extended) to cover both bindings.  All …
> add bindings for LLVMGet{I,F}CmpPredicate

- src/basic_block.rs
Like many other structs in this crate, `BasicBlock` is under-the-hood just a wrapper around an LLVM ref; however, unlike most similar structs, it doesn't implement `Clone` or `Copy`.  I added derives for `Clone` and `Copy` (and while I was at it, `Hash`).  I'm presuming that this won't be contentious, unless I'm missing something about how `BasicBlock` behaves.
None; can make one if discussion is needed.
All tests still pass after this patch has been applied to the `llvm7-0` branch.  Not tested with other branches, or on platforms other than macOS.
> Derive Clone, Copy, and Hash for BasicBlock

- src/values/call_site_value.rs
`CallSiteValue` is another wrapper around `Value` that didn't get `Clone` and `Copy` derived on it (whereas most other `Value` wrappers have those traits).  Similar to #88, I added `Hash` again while I'm here.
None; can make one if discussion is needed.
All tests still pass after this patch has been applied to the `llvm7-0` branch. Not tested with other branches, or on platforms other than macOS.
> Derive Clone, Copy, and Hash for CallSiteValue

- src/builder.rs
- src/types/array_type.rs
- src/types/float_type.rs
- src/types/int_type.rs
- src/types/mod.rs
- src/types/ptr_type.rs
- src/types/struct_type.rs
- src/types/vec_type.rs
- src/types/void_type.rs
- src/values/int_value.rs
- src/values/ptr_value.rs
- src/values/vec_value.rs
- tests/all/test_attributes.rs
- tests/all/test_builder.rs
- tests/all/test_types.rs
- tests/all/test_values.rs
Running inkwell's tests with against an asserts-enabled expensive-checks-enabled, address-sanitizer undefined-behaviour-sanitizer LLVM found some problems. The ones I have fixes for are collected in this branch, the more complicated ones I filed (or will file) bugs for.
This is not yet enough to make inkwell tests run cleanly on my test system, this contains only the parts I think are clean enough to be committed. Most of the changes are to the tests rather than deeper changes that make inkwell safe. I want to work on that too, but I'm going to start with just getting to green (tests passing).
I've marked the changes where I only fixed the test but where inkwell still allows a consumer to trigger the problem.
* const_null() is removed. See \<Breaking Changes\>.
* the element type of a …
> fix misuse of LLVM API found through inkwell tests

- src/types/traits.rs
- tests/all/test_types.rs
Add `ptr_type` and `array_type` functions to BasicType. This allows users of the library to use `BasicTypeEnum`s to create arrays and pointers instead of having to match on every element.
Implementation note:
Since VoidType can't have a pointer to it, I didn't think ptr_type made sense to
implement for AnyType. array_type isn't valid for FunctionType and
VoidType in any case.
https://github.com/TheDan64/inkwell/issues/100
I ran `cargo test` and all new and existing tests passed.
> Add ptr_type and array_type to BasicType

- Cargo.toml
- src/types/int_type.rs
- src/types/mod.rs
- tests/all/test_values.rs
Improve safety of const_int_from_string function by only allowing valid radixes.
const_int_from_string() is still unsafe as the string may contain values outside the range permitted by the radix.
Issue #98.
```
$ cargo test --all --features=llvm7-0 -- test_value_from_string
```
On a Debian Unstable system, testing against my own build of llvm 7.0.1 with assertions enabled. I checked that the assertion fires without this patch.
Callers of `int_type.const_int_from_string` will need to update to use the new enum instead of an integer literal. They can use `StringRadix::from_u8(value).unwrap()`.
> Improve safety of const_int_from_string function by only allowing valid radixes.

- .travis.yml
- README.md
- src/types/traits.rs
- src/values/traits.rs
Implement TryFrom trait for converting BasicValueEnum to ArrayValue, etc. and BasicTypeEnum to ArrayType, etc. This simplifies building generic code with inkwell.
n/a
```
$ cargo test --features=llvm8-0
Finished dev [unoptimized + debuginfo] target(s) in 0.02s
Running target/debug/deps/inkwell-67dab86f6e0441b0
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Running target/debug/deps/all-0e969bb6d979ad9d
running 95 tests
error: process didn't exit successfully: `/home/nick/inkwell/target/debug/deps/all-0e969bb6d979ad9d` (signal: 11, SIGSEGV: invalid memory reference)
```
¯\\\_(ツ)\_/¯
Honestly, I was planning to let inkwell Travis-CI run the PR after I create it since it seems to have the configuration where tests pass and I don't.
> Add TryFrom traits from BasicValueEnum and BasicTypeEnum.

- src/passes.rs
- tests/all/test_passes.rs
LLVMInitializeFunctionPassManager and LLVMFinalizeFunctionPassManager are only applicable to FunctionPassManagers, not all types of PassManager. Move those two functions to their own `impl` block so that they are only provided for that specialization.
Issue #91 .
```
$ /home/nicholas/inkwell/target/debug/deps/all-3f9595a010399385 --nocapture --test-threads 1 test_passes
running 3 tests
test test_passes::test_init_all_passes_for_module ... ok
test test_passes::test_pass_manager_builder ... ok
test test_passes::test_pass_registry ... ok
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 92 filtered out
```
Two methods are removed from `PassManager<T>` and are only available on `PassManager<FunctionValue>`. This may cause a build failure for callers of those methods on …
> Move PassManager::{initialize,finalize} to PassManager<FunctionValue>.

- src/execution_engine.rs
Because `Error::description` is soft-deprecated and `Error::cause` is deprecated (and replaced by `Error::source`) from `1.33`, the current implementation 
https://github.com/TheDan64/inkwell/blob/eb210cd235f6da087c825cfc536d28f3f777bf1d/src/execution_engine.rs#L25-L35
can be replaced simply by:
```rust
impl Error for FunctionLookupError {}
```
> Use default implementation of Error trait

- src/basic_block.rs
Both LLVMGetNextBasicBlock and LLVMGetPreviousBasicBlock unconditionally dereference members off the block's parent. That ends badly when it doesn't have a parent.
```
LLVMBasicBlockRef LLVMGetNextBasicBlock(LLVMBasicBlockRef BB) {
BasicBlock *Block = unwrap(BB);
Function::iterator I(Block);
if (++I == Block->getParent()->end())
return nullptr;
return wrap(&*I);
}
```
Related to issue #93 , but not a complete fix.
before:
```
$ target/debug/deps/all-c57b01cc5b0c609a --nocapture --test-threads 1
running 95 tests
test test_attributes::test_attributes_on_call_site_values ... ok
test test_attributes::test_attributes_on_function_values ... ok
test test_attributes::test_enum_attribute_kinds ... ok
test test_attributes::test_string_attributes ... ok
test …
```
> A block without a parent doesn't have a next/previous. Return None in those cases.

- examples/kaleidoscope/main.rs
- src/values/fn_value.rs
- tests/all/test_basic_block.rs
It's an invariant in LLVM that the first basic block in a function is the entry block, therefore `get_entry_basic_block` and `get_first_basic_block` are redundant. The main difference is that `get_entry_basic_block` assumes that there is at least one child block (aka. the llvm::Function is a definition instead of a declaration) and will execute undefined behaviour if it does not, while `get_first_basic_block` returns a nullptr on function declarations.
n/a
Modified kaleidoscope runs, test_basic_block tests pass.
Removes the `get_entry_basic_block` function, callers should use `get_first_basic_block.unwrap()` instead. The behaviour is the same except that when the unwrap fails it does so in a Rust way, instead of executing undefined behaviour inside of LLVM C++ code.
> Remove get_entry_basic_block and make get_first_basic_block return None when llvm returns nullptr.

- .travis.yml
- Cargo.toml
- src/targets.rs
Conditional compilation for different targets.
This PR adds support for conditional compilation, to support the case when the version of LLVM used is not built for different targets (in the case of windows, we only support `X86`).
We have been testing this in Wasmer.
There are no breaking changes, as by default all the target features are checked.
> Added target as features

- Cargo.toml
- src/context.rs
- src/execution_engine.rs
- src/lib.rs
- src/module.rs
- src/passes.rs
- src/targets.rs
- src/types/int_type.rs
- src/types/ptr_type.rs
- src/types/traits.rs
LLVM requires that clients call its initializers non-concurrently. As the comment in the implementation of TargetRegistry.cpp says:
```
// Clients are responsible for avoid race conditions in registration.
```
and TargetRegistry.h says
```
/// Clients are responsible for ensuring that registration doesn't occur
/// while another thread is attempting to access the registry. Typically
/// this is done by initializing all targets at program startup.
```
on the RegisterTarget method, which is used under the hood by the LLVMInitialize methods for targets.
Use a `std::sync::RwLock` to serialize access to LLVM's list of targets. For initialization, the parts of each target are wrapped individually so that you can change the `InitializationConfig` and run the initializer function again, and …
> Use std::sync::RwLock to make LLVM target registry access thread-safe.

- src/module.rs
- tests/all/test_module.rs
Don't allow a module to link in another module owned by an `ExecutionEngine`.
Fixes #90 
Tests 👍👍
Breaking fix makes error safe instead of UB
@nlewycky Do you think this is a sufficient fix?
> Don't allow linking in owned module

- src/values/instruction_value.rs
- tests/all/test_instruction_values.rs
Adds the ability to get and set alignment on instructions. Copied the approach of getting and setting volatile. Added tests for volatile too when adding tests for alignment.
Related to issue #110. This doesn't add the type safety discussed in that issue, which is closer to #8 and #16. 
Tests!
> Add set_alignment and get_alignment on InstructionValue.

- src/values/instruction_value.rs
- tests/all/test_instruction_values.rs
Similar to what we did for alignment, check that `get_volatile` and `set_volatile` apply to the underlying kind of value before calling the LLVM API to manipulate the Value. LLVM will do a checked-cast to `LoadInst` and if the value is not a load, it will do an unchecked-cast to `StoreInst`. If the value is not a load or store, LLVM has undefined behaviour.
This is a cleanup after pull request #114. That PR was made by copying the style used by the volatile setters and getters. Since we improved it in code review, it makes sense to go back and apply those same changes to volatile.
`cargo test --features=llvm8-0 --all -- test_instruction_values`
`get_volatile` and `set_volatile` are changed to return `Result`s. This is necessary when the type of instruction is incorrect.
> Make set/get_volatile check the type of value.

- src/values/instruction_value.rs
- tests/all/test_instruction_values.rs
Two new methods to get and set the atomic ordering on load and store instructions.
Fixes issue #111.
The safety checks don't check that alignment is set because the caller may choose to set them in the other order. This is "fine" in the sense that it won't cause LLVM to execute undefined behaviour on the spot, but it would cause a verifier failure if you attempt to optimize or generate code for loads and stores with atomic orderings but no alignment.
`cargo test` passed!
> Add {set,get}_atomic_ordering to instruction_value.

- src/values/int_value.rs
- tests/all/test_values.rs
Of course in LLVM you can have a value which is a Constant, and an int, but not a ConstantInt. Add `is_constant_int()` method on `IntValue`.
Also fixes the safety test on `get_zero_extended_constant` and `get_sign_extended_constant` since those both require ConstantInt, not Constant with IntegerType.
n/a. Needed this in wasmer, finally wrote a test and sending in the PR.
New testcase creates constant expression `i32 ptrtoint (void ()* @0 to i32)` and checks it against `is_const` and `is_constant_int`. This testcase is a bit special in that we use the builder but never create an instruction with it. It must create a constant expression instead.
> Add IntValue::is_constant_int() which is true iff is_const() and the int value is not a constant expression.

- src/memory_buffer.rs
- tests/all/test_module.rs
When using Module::parse_bitcode_from_buffer_in_context(), the memory
buffer contains bytes, not a string.
> MemoryBuffer::create_from_memory_range should take &[u8], not &str

- src/types/int_type.rs
> Added missing return 'ctx lt to const_int_from_string

- src/context.rs
- tests/all/test_instruction_values.rs
Changes Context::metadata_node to take a list of BasicMetadataValueEnums instead of BasicValueEnums. This allows us to put metadata strings and other metadata nodes inside metadata nodes.
Adds a test for each type of value that we can insert.
We use this to build up TBAA (type-based aliasing analysis) metadata in the Wasmer LLVM backend.
> Change Context::metadata_node to take a list of BasicMetadataValueEnums.

- Cargo.toml
This PR adds a cargo feature, `no-llvm-linking`, that enables a feature with the same name in `llvm-sys` which prevents `llvm-sys` from telling rust to link LLVM in its bulid.rs.
Discussed beforehand, apologies for the lack of issue.
It worked with `patch` locally, this change doesn't introduce much change on the inkwell side.  I have run into some issues on the Wasmer side landing this and don't have the bandwidth to fully investigate it right now.  It looks like we just need to do more on our side to ensure that LLVM gets properly linked in.
> Add `no-llvm-linking` feature to prevent linking LLVM while building

- src/builder.rs
- tests/all/test_values.rs
I added checks that the types passed to `build_malloc` and `build_array_malloc` are sized before shelling out to `llvm-sys`. One annoying thing about the implementation is that it has to match on the `BasicTypeEnum` because there isn't another way (as far as I know) to check `is_sized`. There are a few functions like this in `inkwell` where QOL could be improved in the future. For now I think this is fine, though maybe I should have left a TODO there.
[Fixes this issue.](https://github.com/TheDan64/inkwell/issues/150)
I added two new checks to `test_allocations` which ensure `build_malloc` and `build_array_malloc` panic when handed unsized types (instead of segfaulting). I also ran the entire existing test suite and all tests pass.
> Build malloc fix

- src/module.rs
- src/support/mod.rs
- src/targets.rs
- tests/all/test_module.rs
- tests/all/test_targets.rs
I added a new struct, `inkwell::targets::TargetTriple` that models a target triple more explicitly in the type system. I fixed the bug where `Module::set_target` and `Module::get_target` were operating on a target rather than a target triple. I also updated all of the functions in the inkwell API which deal with target triples (I think I got all of them at least) to use the `TargetTriple` struct. Corresponding changes were made to the documentation.
`TargetTriple` is a thin wrapper around an `LLVMStringOrRaw`. I modeled `TargetTriple` after `DataLayout`, which achieves a similar aim albeit for a different part of the API. So, even though there are a good number of breaking changes here, the end result is consistent with other parts of the already existing API.
The only part of the …
> Set target fix

- src/types/array_type.rs
- src/types/enums.rs
- src/types/float_type.rs
- src/types/int_type.rs
- src/types/mod.rs
- src/types/ptr_type.rs
- src/types/struct_type.rs
- src/types/traits.rs
- src/types/vec_type.rs
- tests/all/test_types.rs
BasicTypeEnum does not have a size_of() so I have to match the enum and dispatch to the correct type. Better to support it directly.
> Introduce size_of() on BasicTypeEnum

- src/basic_block.rs
- tests/all/test_basic_block.rs
LLVM has replaceAllUsesWith for BasicBlocks as well as other Values. Add an implementation of that method to BasicBlock.
#159
Added a doc-test and checked that it passes, and doesn't pass if I change the assert. Tested on llvm8-0 in a release+asserts build.
> Add an implementation of replace_all_uses_with for BasicBlock.

- src/basic_block.rs
- src/values/mod.rs
- tests/all/test_basic_block.rs
Replacing a value with itself is a no-op, but LLVM can enter an infinite loop. Infinite loops are UB in C++, let's just not do that.
Ran into this after fixing #160, doh.
`cargo test --features=llvm8-0`
> Check for RAUW'ing a value with itself. That's just a no-op.

- src/values/instruction_value.rs
> Yup, calling LLVMIsTailCall on a non-CallInst is UB.

- src/builder.rs
- tests/all/test_builder.rs
Add `build_memcpy` and `build_memmove` LLVM intrinsics.
https://github.com/TheDan64/inkwell/issues/145#issuecomment-600399438
TODO
> Add build_memcpy and build_memmove

- .travis.yml
- Cargo.toml
- internal_macros/src/lib.rs
- src/lib.rs
- src/values/instruction_value.rs
- src/values/metadata_value.rs
- tests/all/test_attributes.rs
- tests/all/test_passes.rs
- tests/all/test_targets.rs
- tests/all/test_values.rs
This is a minimal update to support LLVM 9 and LLVM 10. This doesn't add support for all new features of the newer compiler, it does the minimum to compile and make the tests pass.
n/a
1. `cargo test --features=llvm10-0`.
1. Change cargo.toml to depend on `llvm-sys = "90.0"` and `cargo test --features=llvm9-0`.
> Add support for LLVM 9 and LLVM 10.

- src/values/basic_value_use.rs
- src/values/enums.rs
- tests/all/test_instruction_values.rs
Change BasicValueUse::get_user to return an AnyValueEnum.
To make the tests pass, we need to improve AnyValueEnum too. When construction an AnyValueEnum with a void Value, choose the InstructionValue enum, for example a StoreInst. Implement the into_X_value() methods so that we can use the contained value.
#162 
`cargo test --features=llvm8-0`
The return type of the function changed, callers may have to adjust.
> Change BasicValueUse::get_user to return an AnyValueEnum.

- src/basic_block.rs
- src/values/basic_value_use.rs
- tests/all/test_basic_block.rs
Makes it possible to get a `BasicValueUse` for a `BasicBlock`.
#161 
`cargo test --features=llvm10-0`
> Add BasicBlock::get_first_use().

- src/object_file.rs
The first section usually has no name, and LLVM returns a nullptr. Inkwell will dereference that to return the `&CStr`. The same thing should be able to happen with a `Symbol` but I haven't observed that myself. When LLVM returns a nullptr string as the name, return None.
#173 
Tried dumping names of all symbols and sections on a few object files.
`get_name` now returns an Option instead of a `&CStr`.
It might be possible to return an empty string &CStr, but I tried and failed.
> Make symbol and section names optional, for when llvm returns a nullptr.

- src/targets.rs
In the current API, Rust requires that the `IntType` returned by `ptr_sized_int_type_in_context` not outlive the `TargetData`, but in reality it's owned by the `Context` and goes away with the `Context` independent of the `TargetData`.
n/a. (This fix was required to write tests in #174.)
`cargo test --features=llvm8-0`
This might be breaking? I think it's strictly more permissive, but I'm not certain.
> Make `target_data.ptr_sized_int_type_in_context` return an IntType with lifetime from the context.

- src/object_file.rs
- tests/all/main.rs
- tests/all/test_object_file.rs
Don't increment the iterator while a Section/Relocation/Symbol is using it.
#172 
There aren't unit tests for object_file yet. I think that in order to add some, we will need some binary test files in the inkwell tree. Thoughts?
As for for I tested it, the simple test driver program is:
```rust
use inkwell::memory_buffer::MemoryBuffer;
use std::path::Path;
fn main() {
let mb = MemoryBuffer::create_from_file(Path::new("test.o")).unwrap();
let obj = mb.create_object_file().unwrap();
let mut first = true;
for section in obj.get_sections() {
dbg!("<section>");
if !first {
dbg!(section.get_name());
} else {
first = false;
}
dbg!(section.size());
dbg!(section.get_address());
for rel in section.get_relocations() {
dbg!(rel.get_offset());
/*
for symbol in rel.get_symbols() {
dbg!("<relocation …
```
> Don't increment the iterator while a Section/Relocation/Symbol is using it.

- src/object_file.rs
- tests/all/test_object_file.rs
The trouble with a CStr is that it ends at the first NUL byte. This can lead to section contents appearing to be shorter than the reported size of the section.
Section::get_contents() is changed to return a &[u8] instead of a CStr and a test is added.
n/a
cargo test --features=llvm8-0
Yes, a change in type. It appears that CStr follows the C string semantics of ending at the first NUL byte. Object file sections may contain arbitrary data including NUL bytes. Some change of type is unavoidable.
LLVM doesn't document the lifetime of the returned pointer, but my inspection of the ELFObjectFile implementation shows that it's returning a pointer into their buffer of the whole object file, so it outlives the section iterator and lives as long as the object file object. Hopefully `&[u8]` is fine …
> Section contents are arbitrary byte sequences, return a &[u8] for them instead of a CStr.

- src/values/instruction_value.rs
- tests/all/test_instruction_values.rs
If building for llvm 10+, permit get_volatile and set_volatile on atomicrmw and cmpxchg instructions.
n/a
I've only checked that it builds.
The error message changed to include the additional instructions in the list. Anyone with code relying on that string will find that it doesn't match. It would be surprising if anyone wrote code relying on that string, since it was the only possible string it could return.
> Get/set of volatile on atomicrmw and cmpxchg was added in LLVM 10.

- src/context.rs
- src/lib.rs
This PR adds support for inline asm calls.
Closes #204 
The example for the added method should add asm that calls the exit syscall with status 1.
I have also tested this locally and everything appears to work as intented.
No breaking changes.
> Add call asm

- Cargo.toml
- build.rs
Adds a feature `no-libffi-linking` (not enabled by default) that stops linking to libffi by default. 
https://github.com/TheDan64/inkwell/issues/206
Building with the feature enabled no longer forces any dependency on libffi which is what I wanted to achieve.
> Add feature to disable linking to libffi

- examples/kaleidoscope/main.rs
``` Lexer { input: input, .... } ``` looks redundant. So I think ``` Lexer { input, .... } ``` is better expression.
Nothing.
run command ```  cargo run --example kaleidoscope --features "llvm10-0" ``` and type "1 + 1" and  "exit".
nothing.
> rewrite redundant expression

- src/debug_info.rs
- src/values/global_value.rs
- tests/all/test_debug_info.rs
Added support for global variable expressions in debug info, as well as Global variables metadata
This enables adding debug information to global variables so they can be recognized as variables in a debugger
[216](https://github.com/TheDan64/inkwell/issues/216)
The C API does not allow retrieving metadata set on global variables (as opposed to instructions). 
The tests will generate an IR of the global variable and make sure the metadata is added to it.
> Add support for global variable expressions in debug info

- src/context.rs
- src/types/array_type.rs
- src/types/float_type.rs
- src/types/fn_type.rs
- src/types/int_type.rs
- src/types/ptr_type.rs
- src/types/struct_type.rs
- src/types/traits.rs
- src/types/vec_type.rs
- src/types/void_type.rs
- src/values/array_value.rs
- src/values/float_value.rs
- src/values/fn_value.rs
- src/values/int_value.rs
- src/values/phi_value.rs
- src/values/ptr_value.rs
- src/values/struct_value.rs
- src/values/traits.rs
- src/values/vec_value.rs
- tests/all/test_module.rs
- tests/all/test_types.rs
- tests/all/test_values.rs
Make it easier to print a BasicValueEnum/BasicTypeEnum
> Add print_to_string() to Any{Value,Type}

- src/module.rs
- src/values/metadata_value.rs
This patch fixes multiple memory leaks.
One pattern I noticed (in `Module::get_global_metadata` and in `MetadataValue::get_node_values`) is the following:
1. Allocate a new `Vec<T>`,
2. Get a mutable pointer to it,
3. Forget the vector,
4. Fill the vector with `LLVM*`,
5. Read back the vector as a slice,
6. Map slice values, and collect them in a newly allocated vector.
Here, the first vector is lost. That's a memory leak.
This patch changes the steps 3 to 6: We use `Vec::with_capacity` to
get a buffer to fill with `LLVM*`, and we set back the length to `count`
with `Vec::set_len` once the buffer is completed. The code is more
Rust-FFI-idiomatic and simpler.
Compiling and running the documentation of the `get_global_metadata`
method, valgrind gives us the following results:
(`master`)
``` …
```
> fix(module,values) Fix memory leaks

- .travis.yml
- Cargo.toml
- README.md
- internal_macros/src/lib.rs
- src/debug_info.rs
- src/lib.rs
- src/module.rs
- src/types/enums.rs
- src/values/instruction_value.rs
- src/values/metadata_value.rs
- tests/all/test_attributes.rs
- tests/all/test_debug_info.rs
- tests/all/test_instruction_values.rs
- tests/all/test_passes.rs
- tests/all/test_values.rs
Added support for an LLVM 11 future.
Updated the debug builder API to support the new parameters
Fixed some failing tests
Updated travis config 
#217 
Ran tests for the older features and the new feature
Did not add new tests as no new functionality was added
**2 Tests are still failing on my machine**, one for enums and one for alignment.
> Add support for LLVM 11

- src/types/enums.rs
Every BasicType can take on a zero value. Add BasicTypeEnum::const_zero() that returns a BasicValueEnum with the zero in it, of the matching basic type.
n/a
doc test
> Add BasicTypeEnum::const_zero().

- README.md
- src/types/enums.rs
- src/values/enums.rs
From 1.42.0, the [matches!](https://doc.rust-lang.org/std/macro.matches.html) macro is provided.
None
It's ok if all existing tests passed.
> Refactor: use matches! in is_xxx functions instead of if-let expression.

- src/types/enums.rs
- src/values/enums.rs
Provide more detailed panic message when a conversion from an enum to a specific variant fails.
ran test suite
> More detailed into-x error messages

- src/builder.rs
- src/values/callable_value.rs
- tests/all/test_builder.rs
Adds support for the `invoke` instruction, and some support for building landing pads and resuming an exception. This does not cover the full exception functionality, but unless you're building a c++ compiler this should provide most useful features.
> Invoke & some friends

- Cargo.toml
- src/attributes.rs
- src/context.rs
- tests/all/test_attributes.rs
I have extended the api for `Context` and for `Attribute` to add support for type attributes.
This includes wrapping 3 new ffi calls: 
- [LLVMCreateTypeAttribute](https://docs.rs/llvm-sys/120.2.0/llvm_sys/core/fn.LLVMCreateTypeAttribute.html)
- [LLVMGetTypeAttributeValue](https://docs.rs/llvm-sys/120.2.0/llvm_sys/core/fn.LLVMGetTypeAttributeValue.html)
- [LLVMIsTypeAttribute](https://docs.rs/llvm-sys/120.2.0/llvm_sys/core/fn.LLVMIsTypeAttribute.html)
The added api was based in the old api for attributes.
#260 
I have added tests in `inkwell/tests/all/test_attributes.rs` as well as doc tests in each of the methods added. Only tested with llvm version `12.0.1` through `cargo test --features "target-all,llvm12-0"`.
Also I had been tested during development of my front-end at …
> Add type attribute api.

- src/targets.rs
Derive `Copy` & `Clone` for simple, value enums. 
#264 
Not necessary.
Changes the public interface for a few enums. Shouldn't break anything.
> Derive Copy & Clone for enums (#264)

- src/passes.rs
- tests/all/test_passes.rs
Exposes the `mergefunc` optimization pass to _Inkwell_ through `LLVMAddMergeFunctionsPass` function in _llvm-sys_
#267 
Built and tested under `llvm8-0` and `llvm11-0` (versions I readily have available).  Correct feature flag based off of presence of function in upstream `llvm-sys` (https://docs.rs/llvm-sys/100.2.2/src/llvm_sys/transforms/ipo.rs.html).
> Add passthru for 'MergeFunctionsPass'

- src/module.rs
`cargo build --target wasm32-wasi --features llvm11-0` fails with:
--> /home/sean/git/inkwell/src/module.rs:601:95
|
601 |     pub fn write_bitcode_to_file(&self, file: &File, should_close: bool, unbuffered: bool) -> bool {
|            ---------------------                                                              ^^^^ expected `bool`, found `()`
|            |
|            implicitly returns `()` as its body has no tail or `return` expression
Note that as_raw_fd() cannot be used on wasi yet, since this depends on
wasm_ext which is unstable:
https://github.com/rust-lang/rust/issues/71213
> Fix wasm build

- Cargo.toml
- src/types/int_type.rs
Replaces the use of regex matching in `int_type.rs` with features from the stdlib. The main benefit is that the `regex` crate can be moved to [ `dev-dependencies`](https://doc.rust-lang.org/rust-by-example/testing/dev_dependencies.html)  and is therefore not compiled when using inkwell as a dependency.
I also generally don't like regex too much and think the rust code is nicer, but that's a matter of taste.
Regex is still used in `tests/all/test_targets.rs`, with this beauty:
```rust
let datalayout_specification_re = Regex::new("[Ee]|S\\d+|P\\d+|A\\d+|p(\\d+)?:\\d+:\\d+(:\\d+)?|i\\d+:\\d+(:\\d+)?|v\\d+:\\d+(:\\d+)?|f\\d+:\\d+(:\\d+)?|a:\\d+(:\\d)?|F[in]\\d+|m:[emoxw]|n\\d+(:\\d)*|ni:\\d+(:\\d)*").unwrap();
```
I'm not going to touch that one.
tests pass.
> remove regex dependency (outside of tests)

- src/builder.rs
- tests/all/test_builder.rs
I added a memset function similar to the memcpy and memmove
Fixes #145
Added unit tests similar to the memmove and memcpy
I also fixed the memmove test to actually call memmove not memcpy
> Add support for memset

- README.md
```
warning: unused imports: `InitializationConfig`, `Target`
--> src/main.rs:6:24
|
6 | use inkwell::targets::{InitializationConfig, Target};
|                        ^^^^^^^^^^^^^^^^^^^^  ^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```
> Remove unused imports in README example

- Cargo.toml
- src/targets.rs
Add RISCV AsmParser/AsmPrinter/Disassembler support on initialize_riscv.
https://github.com/TheDan64/inkwell/issues/291
`cargo test --features llvm13-0`
> Add RISCV AsmParser/AsmPrinter/Disassembler support

- src/intrinsics.rs
- src/lib.rs
- tests/all/main.rs
- tests/all/test_intrinsics.rs
- Add a new type - Intrinsic which acts as a wrapper around intrinsic id. It guarantees that it contains a valid intrinsic id in it
- Add a function Intrinsic::find to safely create instances of Intrinsic
- Add a function Intrinsic::get_declaration which wraps LLVMGetIntrinsicDeclaration and allows getting a declaration of intrinsic in a module
#300 
Written several unit tests covering normal usages and corner-cases that I could think of. 
Couldn't run clippy, it gives a ton of errors & warnings of code that I didn't write =(
Will write docs if the API gets approved =)
> [WIP] Expose API for getting declarations of intrinsics

- src/values/call_site_value.rs
- src/values/fn_value.rs
- tests/all/test_attributes.rs
Add functions to `FunctionValue` and `CallSiteValue` that give back a vector with all attributes at a particular location on that value.
LLVM primitives have existed since llvm 3.9. The tricky bit here is that we need to give LLVM a pointer that it writes the attributes into. This requires `MaybeUninit` to do safely. Afterwards we transmute the `MaybeUninit` away (the alternative would create a second vector which is undesirable).
Testing is done similarly to the `count_attributes` functions. We check the attributes we get back are as expected after adding/removing attributes.
---
as an aside: following the standard `cargo fmt` formatting rules would make contributing much easier/fun for me.
> Get all function/callsite attributes as a vector

- src/module.rs
- src/passes.rs
- tests/all/test_passes.rs
Added a method to the `Module` to run the llvm passes
Issue #309 
I tested this on a separate project.
I am not sure what kind of tests I could add to the module here, suggestions are appreciated.
The change only applies from LLVM13, as the API was introduced then, the feature flags are set appropriately
> Add the runpasses option to the module

- src/builder.rs
- tests/all/test_builder.rs
The current `build_int_cast` uses `LLVMBuildIntCast`, which is [always
signed and is deprecated](https://github.com/hdoc/llvm-project/blob/a6ad3505abc7409abd2a4118338b9c85ec2e9f09/llvm/include/llvm-c/Core.h#L3939-L3941).
This commit adds a function that uses `LLVMBuildIntCast2`, which
correctly casts ints to unsigned int types if asked to do so.
> Add a function to build int casts that respect the target signed-ness

- src/values/fn_value.rs
- tests/all/test_object_file.rs
Currently, it's only possible to set sections for `GlobalValue`s. In certain cases (e.g., for BPF programs) you need to set specific sections for functions too. This PR adds the corresponding public API for `FunctionValue`.
> Add API to set a section for function values

- src/values/instruction_value.rs
- tests/all/test_instruction_values.rs
I added a new function to the `InstructionValue` module to get type of an instruction.
https://github.com/TheDan64/inkwell/issues/321
I created unit tests and tested them with LLVM 13.0 under a Linux environment.
N/A
> API to get type of InstructionValue

- src/context.rs
- src/intrinsics.rs
- src/types/enums.rs
- src/types/float_type.rs
- src/types/int_type.rs
- src/types/metadata_type.rs
- src/types/ptr_type.rs
- src/types/void_type.rs
- tests/all/test_builder.rs
- tests/all/test_debug_info.rs
- tests/all/test_phi_conversion.rs
Fix warnings by removing unused imports.
Also fixes the build error that's caused by an unused doc comment.
> Fix warnings by removing unused imports

- src/types/array_type.rs
- src/types/enums.rs
- src/types/float_type.rs
- src/types/fn_type.rs
- src/types/int_type.rs
- src/types/metadata_type.rs
- src/types/ptr_type.rs
- src/types/struct_type.rs
- src/types/vec_type.rs
- src/types/void_type.rs
In this PR, I implemented the function `print_to_string` for all existing LLVM Types, which prints the type definition to LLVMString.
This function will be used to implement the `Display` trait for all existing LLVM Types in the folder https://github.com/TheDan64/inkwell/tree/master/src/types
There is no issue discussing the `print_to_string` before, so maybe we can discuss directly in this PR, instead of creating a new issue?
The function `print_to_string` is basically a wrapper function that expose the `print_to_string` of the corresponding underlying type of each LLVM Type, like below:
``` rust
/// Print the definition of a `FloatType` to `LLVMString`.
pub fn print_to_string(self) -> LLVMString {
self.float_type.print_to_string()
}
```
So, maybe unit test is not necessary?
No breaking …
> print LLVM Types to LLVMString and implement Display trait

- src/module.rs
- src/values/array_value.rs
- src/values/call_site_value.rs
- src/values/callable_value.rs
- src/values/enums.rs
- src/values/float_value.rs
- src/values/fn_value.rs
- src/values/global_value.rs
- src/values/instruction_value.rs
- src/values/int_value.rs
- src/values/metadata_value.rs
- src/values/phi_value.rs
- src/values/ptr_value.rs
- src/values/struct_value.rs
- src/values/traits.rs
- src/values/vec_value.rs
- tests/all/test_debug_info.rs
Hi,
This PR implements the `Display` trait for the current LLVM Values. This feature is currently missing in the current code base.
It is related to PR https://github.com/TheDan64/inkwell/pull/327, but implement for LLVM Value instead.
The trait Display is implemented by simply calling the function `print_to_string` from the trait `AnyValue`, like below. 
``` rust
use super::AnyValue;
....
impl Display for IntValue<'_> {
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
write!(f, "{}", self.print_to_string())
}
}
```
Test cases of the function `print_to_string` are already included in the `tests` directory.
So, maybe more unit tests are not necessary.
No breaking changes.
> implement print_to_string and Display trait for LLVM Values

- src/attributes.rs
- src/types/int_type.rs
- src/types/metadata_type.rs
- src/types/ptr_type.rs
- src/values/traits.rs
- tests/all/main.rs
remove an assert that makes `get_enum_kind_id` panic when given a type attribute. 
I'm not entirely sure what the difference is between enum and type attributes. It looks like enum is a superclass. By default they have integer values, but since version 12.0 they can also have type as the value. And then some specific functions are added for type attributes, but specifically the kind ID is still only available with the "enum" functions, e.g. `get_named_enum_kind_id`.
So the choice I made here is that inkwell should give the same answer as LLVM for a type attribute, rather than panicking.
An alternative is to add a new function `get_type_kind_id` which has the same implementation as `get_enum_kind_id` and would assert that `attribute.is_type()`.
Finally, some docs in the module hint at a …
> make get_enum_kind_id work on type attributes

- src/builder.rs
- src/module.rs
- src/values/callable_value.rs
- src/values/ptr_value.rs
All functions deprecated since llvm14 are replaced with recommended alternatives.
Other deprecations (e.g. `LLVMSetCurrentDebugLocation` in `builder.rs`, deprecated since llvm9.0 ) are **untouched**.
I thought it might fix SEGV in https://github.com/TheDan64/inkwell/issues/343, but actually it doesn't.
However, such deprecation removal is always recommended and seems to have no room to argument, I just have directly opened this issue 😃.
I have run test on Ubuntu22.04 LTS (x86_64 VM instance).
Since this is change only related to `llvm14-0` feature, I tested with:
```shell
cargo test --target=x86_64-unknown-linux-gnu --features=llvm14-0 --all
```
All tests and doctests are successfully passed.
It does not break existing APIs, but I added implementation of `AsTypeRef` for `CallableValue` in …
> Replace deprecated functions in LLVM14 with new ones

- src/debug_info.rs
- tests/all/test_debug_info.rs
The debug info can now create a pointer or array type
Arrays support multiple dimensions passed as ranges
Fixes #348 
Created smoke tests insuring the call into the DI builder returns a type
> Add support for pointer and array debug types 

- .github/workflows/test.yml
Modified GitHub Actions configuration to publish documentation on every push to `master`. It will only do so if the `tests` action succeeds, so we will not be publishing documentations for broken versions.
Probably related to #2.
The workflow runs correctly in my fork (see the log [here](https://github.com/ruifengx/inkwell/actions/runs/3187875220)), and here is the rendered documentation: <https://ruifengx.github.io/inkwell/>.
**EDIT:** note that I arranged the action to only build for `llvm14-0`. Please check if this is the desired behaviour. Also, the documentation looks very different from the old one, so please confirm it looks correct.
> publish docs for each commit

- src/values/enums.rs
This PR change the constructors of AnyValueEnum to properly create a FunctionValue instead of PointerValue from LLVMValueRef, and thus addressed the error when calling 'into_function_value'.
#71 
LLVM version 14.0, i just modified it to properly run in my project, so only a bit of testing is done.
> change AnyValueEnum constructor to fix Issue #71

- src/context.rs
Unwrap ContextImpl to get the LLVMContextRef before returning from get_ref.
Closes #363.
Tested by compiling Inkwell. It seems like CI doesn't build with the internal-getters feature.
> Fix `get_ref` for contexts

- src/types/array_type.rs
- src/types/enums.rs
- src/types/float_type.rs
- src/types/fn_type.rs
- src/types/int_type.rs
- src/types/metadata_type.rs
- src/types/ptr_type.rs
- src/types/struct_type.rs
- src/types/vec_type.rs
- src/types/void_type.rs
Makes types' `new` method public
Look at the arguments provided in #366 .
TLDR why need this:
1. Frequent API changes in llvm
2. Interoperation with different wrappers
Implements #366 
Runned tests with `cargo test --all --target=aarch64-apple-darwin --features=llvm14-0`
> Public new

- src/values/fn_value.rs
- src/values/global_value.rs
- src/values/mod.rs
- tests/all/test_object_file.rs
- tests/all/test_targets.rs
Move repeated code for `get_section` and `set_section` for `GlobalValue` and `FunctionValue` to derive macro
Added new derive macro `Section`.
First steps to fix test error inside `test_object_file` as in issue #345.
Later `cfg(target_os = "macos")` maybe used inside this single macro, to fix this problem.
I tried to implement this fix with replacing `"section_name"` to `",section_name"` , but now I have test errors instead of LLVM ERROR
`cargo test --all  --target=aarch64-apple-darwin --features=llvm14-0`
> Move get/set section to derive macro

- src/context.rs
- src/module.rs
- tests/all/test_context.rs
Added `context.get_type("name")` method
Added new method with documentation and tests to context. It uses `LLVMGetTypeByName2` from llvm_sys, which was missing in inkwell.
Related to my question: #367 
Test when type is found and when not found.
> Add method to get type by its name

- src/types/enums.rs
- src/values/enums.rs
While using inkwell, I found some useful enum conversions to be missing. It's just inconvenient to implement them outside of inkwell, so why not add it.
Adds:
* `TryFrom<AnyTypeEnum<'ctx>> for BasicMetadataTypeEnum<'ctx>`
* `TryFrom<BasicMetadataTypeEnum<'ctx>> for BasicTypeEnum<'ctx>`
* `TryFrom<AnyValueEnum<'ctx>> for BasicMetadataValueEnum<'ctx>`
* `TryFrom<BasicMetadataValueEnum<'ctx>> for BasicValueEnum<'ctx>`
P.S: plan to implement `From<BasicMetadataTypeEnum<'ctx>> for AnyTypeEnum<'ctx>` as well, but that requires adding metadata to AnyTypeEnum, that's why it will be in another pull request 
```
cargo test --features llvm14-0
```
> Add new TryFrom implementations for enums

- src/builder.rs
- src/context.rs
- src/debug_info.rs
- src/lib.rs
- src/module.rs
- src/targets.rs
- src/types/array_type.rs
- src/types/float_type.rs
- src/types/fn_type.rs
- src/types/int_type.rs
- src/types/mod.rs
- src/types/ptr_type.rs
- src/types/struct_type.rs
- src/types/traits.rs
- src/types/vec_type.rs
- src/values/basic_value_use.rs
- src/values/instruction_value.rs
- tests/all/test_attributes.rs
- tests/all/test_builder.rs
- tests/all/test_context.rs
- tests/all/test_debug_info.rs
- tests/all/test_execution_engine.rs
- tests/all/test_instruction_conversion.rs
- tests/all/test_instruction_values.rs
- tests/all/test_targets.rs
- tests/all/test_types.rs
- tests/all/test_values.rs
in #383 it came up that the current representation of an address space is not entirely correct. To make changes to that type easier, and because usually "Generic" is the address space that users want, implementing and using the default instance means that even if we change the representation of address spaces, this would not actually be noticeable by users.
There specifically are no breaking changes in the PR
> impl Default for AddressSpace to make future changes easier

- src/context.rs
- src/values/array_value.rs
- src/values/vec_value.rs
- tests/all/test_values.rs
This changes the type signature of `Context::const_string` to return ArrayValue instead of VectorValue.
This alone breaks the `test_values::test_string_values` test, 
so I also added the `is_const_string` and `get_string_constant` methods from VectorValue to ArrayValue.
I didn't remove those methods from VectorValue because I wanted to avoid making any breaking changes. I'm not too sure if they are needed, though.
#390 
- Doc tests
- `cargo test -F llvm14-0`
> Treat `const_string` as returning `ArrayValue`

- src/values/mod.rs
Following the commit [#3917e32](https://github.com/TheDan64/inkwell/commit/3917e3207941c1a90f28df4fe08ffdd26de71575) section have a `,` being added to their name on macOS. On some certain cases, that `,` should not be added because the name is already fully qualified, like `__TEXT,wasmer_function`.
This PR check if section name already contains a comma before adding it.
address issue #396 
Tested with latest Wasmer on macOS , both x86_64 and aarch64 arch.
> Fix macOS section handling that already have a comma in ther name

- src/module.rs
Add a get_globals function similar to get_functions, to allow easier iteration over globals
https://github.com/TheDan64/inkwell/issues/403
Should work since it's a copy-paste of FunctionIterator and get_functions. cargo doc returns compilation errors on master and I'm not sure how to resolve them though.
> Add get_globals

- .github/workflows/test.yml
- Cargo.toml
- examples/kaleidoscope/main.rs
- internal_macros/src/lib.rs
- src/builder.rs
- src/context.rs
- src/debug_info.rs
- src/lib.rs
- src/module.rs
- src/passes.rs
- src/support/mod.rs
- src/types/array_type.rs
- src/types/enums.rs
- src/types/float_type.rs
- src/types/fn_type.rs
- src/types/int_type.rs
- src/types/ptr_type.rs
- src/types/struct_type.rs
- src/types/vec_type.rs
- src/values/float_value.rs
- src/values/metadata_value.rs
- src/values/mod.rs
- tests/all/test_builder.rs
- tests/all/test_debug_info.rs
- tests/all/test_instruction_values.rs
- tests/all/test_passes.rs
- tests/all/test_types.rs
- tests/all/test_values.rs
This PR updates the crate to support building and using LLVM 16. The LLVM changelog can be found [here](https://releases.llvm.org/16.0.0/docs/ReleaseNotes.html), and the llvm-sys MR is [here](https://gitlab.com/taricorp/llvm-sys.rs/-/merge_requests/28). The commit messages contain a more detailed explanation of what was done in each patch, so I recommend reviewing commit-by-commit.
This closes #400.
This was tested by running the CI on the development fork. I also wrote a small test package to verify `support::get_llvm_version()`, but I don't believe it is feasible to test it using the test suite.
> Support LLVM 16

- src/basic_block.rs
- src/values/instruction_value.rs
- tests/all/test_instruction_values.rs
Added function to find an Instruction Value based on its name. I thought it was useful for finding instruction values within blocks based on their name. If for example you create a variable, you could use this function to then find it.
https://github.com/TheDan64/inkwell/issues/415
Tested it within my project to retrieve created variables. Also added doc tests.
> Find a InstructionValue based on its name

- src/types/struct_type.rs
- tests/all/test_types.rs
Allow call of `set_body` on none opaque structs
#417 
Added some test cases in `tests/all/test_types.rs`. There seems to be a issue in changing the `packed` status of a non-opaque type(at least on my pc - a M1 macbook pro), but changing its body is working as expected.
> fix: allow call of `set_body` on none opaque structs

- .github/workflows/test.yml
- src/attributes.rs
- tests/all/test_attributes.rs
Improve test for attributes on functions. Attributes on the `Function` location were not tested at all. The `alignstack` attribute was applied to the return type, but this attribute is not actually valid in that position. A `verify()` on the module called this issue out.
> add test for inlinealways function attribute

- Cargo.toml
I've added `force-dynamic`, `prefer-dynamic`, `force-static`, and `prefer-static` feature flags to Cargo.toml for each version of `llvm-sys` from 12-16 (these flags only became available in version 12).
#427 
`cargo test --features llvm15-0-force-dynamic` runs successfully.  Also tested in a small project using `llvm15-0-force-dynamic` enabled.
> Add llvm-sys linkage features

- Cargo.toml
- src/context.rs
- src/targets.rs
Historically parking_lot's locking types performed better, but since a few Rust releases ago the types provided by the standard library perform well enough. Replacing parking_lot also reduces the number of dependencies.
This fixes https://github.com/TheDan64/inkwell/issues/419.
https://github.com/TheDan64/inkwell/issues/419
By running `cargo test --features llvm16-0` and the equivalent `cargo check` command.
> Replace parking_lot with the standard library

- .github/workflows/test.yml
- _typos.toml
- src/builder.rs
I added the `typos` utility to CI, and simplified the enum variants in the `BuilderError` from #436 .
I added the `typos` utility to CI (and an exclude file).
I also removed the `GEPError` as it did not make sense and the 2 others `GEPPointee` and `GEPIndex` fit better. The 2 lines which used `GEPError` have been replaced to use more the descriptive variants.
This is related to #438.
It also resolves what @marcospb19 raised in #436.
CI, including my new addition to it, is passing.
> Add `typos` to CI

- src/values/struct_value.rs
- tests/all/test_values.rs
Added get_field_at_index and count_fields to StructValue.
This  mirrors the functions from StructType and allows accessing members of const structures directly.
https://github.com/TheDan64/inkwell/issues/450
Added a few simple assertions to the tests.
[test_values.rs](https://github.com/TimZF/inkwell/blob/00ccb05b34c906931586e174d57330425b559715/tests/all/test_values.rs#L1187)
> Added get_field_at_index and count_fields to struct values

- src/values/instruction_value.rs
- tests/all/test_instruction_values.rs
Adding the 3 Functions and the corresponding tests.
-
https://github.com/TheDan64/inkwell/issues/454
Only tested on LLVM-16
> Adding get_allocated_type, is_terminator and is_conditional to InstructionValue

- examples/kaleidoscope/implementation_typed_pointers.rs
- examples/kaleidoscope/main.rs
- https://discourse.llvm.org/t/c-api-for-newpm/70561
- It seems the legacy pass manager has been removed, but there is no C API for the new pass manager
Todo
`cargo run --features llvm15-0 --example kaleidoscope -- --dc`
and
`cargo run --features llvm16-0 --example kaleidoscope -- --dc`
> Update Kaleidoscope example to LLVM 15 and 16

- .github/workflows/test.yml
- Cargo.toml
- README.md
- internal_macros/src/lib.rs
- src/builder.rs
- src/context.rs
- src/debug_info.rs
- src/lib.rs
- src/module.rs
- src/passes.rs
- src/support/mod.rs
- src/types/enums.rs
- src/values/int_value.rs
- src/values/metadata_value.rs
- src/values/mod.rs
- src/values/vec_value.rs
- tests/all/main.rs
- tests/all/test_builder.rs
- tests/all/test_debug_info.rs
- tests/all/test_instruction_values.rs
- tests/all/test_types.rs
- tests/all/test_values.rs
Taken from and closes https://github.com/TheDan64/inkwell/pull/448, fixes https://github.com/TheDan64/inkwell/issues/444.
> Support LLVM 17

- src/module.rs
- src/values/array_value.rs
- src/values/basic_value_use.rs
- src/values/call_site_value.rs
- src/values/float_value.rs
- src/values/fn_value.rs
- src/values/global_value.rs
- src/values/instruction_value.rs
- src/values/int_value.rs
- src/values/metadata_value.rs
- src/values/phi_value.rs
- src/values/ptr_value.rs
- src/values/struct_value.rs
- src/values/vec_value.rs
I only did some of them so llvm-plugin can move off its fork. Example use:
https://github.com/jamesmth/llvm-plugin-rs/blob/7fe29ca68b70538321ba63afc0dd5fc856809488/llvm-plugin/src/analysis.rs#L116
> Expose some LLVMValueRef constructors

- src/values/struct_value.rs
This is the last change needed to allow llvm-plugin to move off its fork:
https://github.com/jamesmth/llvm-plugin-rs/blob/7fe29ca68b70538321ba63afc0dd5fc856809488/examples/strings.rs#L103
> Add set_field_at_index for llvm-plugin

- .github/workflows/test.yml
- examples/kaleidoscope/README.md
The command provided to run example is not valid in my desktop even though I installed the llvm already:
```sh
$ uname -a
Darwin GF9534F26Q 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; 
root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
$ llvm-config  --version
16.0.6
```
A part of error log is shown below:
```
➜  inkwell git:(improve/revise-example-guides) cargo run --example kaleidoscope        
Compiling inkwell v0.2.0 (/Users/yuchen.xie/workspace/rust/inkwell)
error: One of the LLVM feature flags must be provided: llvm4-0 llvm5-0 llvm6-0 llvm7-0 llvm8-0 llvm9-0 llvm10-0 llvm11-0 llvm12-0 llvm13-0 llvm14-0 llvm15-0 llvm16-0 llvm17-0 
--> src/lib.rs:101:9
|
101 |           compile_error!(concat!("One of the LLVM feature flags must be provided: ", $($all, " "),*));
| …
```
> ci: build kaleidoscope in ci and revise example docs

- examples/kaleidoscope/README.md
- examples/kaleidoscope/main.rs
Updating README/comments around kaleidoscope example.
> Fix links in kaleidoscope

- Cargo.toml
- src/lib.rs
Add serde derives for some config datastructures. Otherwise they can not be reused when deriving the compilers configuration (or it has to be implemented manually).
Hidden behind `serde` feature flag so it should be pretty non-invasive.
> Add serde derives for some config datastructures

- Cargo.toml
- README.md
- internal_macros/src/lib.rs
- src/builder.rs
- src/context.rs
- src/debug_info.rs
- src/lib.rs
- src/module.rs
- src/targets.rs
- src/types/enums.rs
- src/values/call_site_value.rs
- src/values/float_value.rs
- src/values/instruction_value.rs
- src/values/int_value.rs
- src/values/metadata_value.rs
- src/values/mod.rs
- tests/all/main.rs
- tests/all/test_builder.rs
- tests/all/test_debug_info.rs
- tests/all/test_instruction_values.rs
- tests/all/test_targets.rs
- tests/all/test_types.rs
- tests/all/test_values.rs
Support [LLVM 18](https://releases.llvm.org/18.1.0/docs/ReleaseNotes.html#id26).
#482
> WIP: Support LLVM 18

- src/builder.rs
- tests/all/test_builder.rs
- tests/all/test_instruction_values.rs
Renamed `bitcast` to `bit_cast`. For consistency with LLVM's `LLVMBuildBitCast` and internal `build_int_cast`,`build_float_cast`,... . 
Closes #485.
To be tested with github CI.
API change from `builder.build_bitcast` to `builder.build_bit_cast`.
- [ x ] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)
> renamed bitcast to bit_cast

- src/values/mod.rs
Simply fixes the conditional compilation code inside values/mod.rs to correctly use the &str type instead of String
#497 
Code was built on a MacOS x86_64 and MacOS Aarch64 machine (13.0 and 13.4) using github actions
On a side note, it may be wise to setup actions to automatically build the project to prevent issues like this.
There hasn't been any testing of the specific section function, but any issues after this change will have existed beforehand, all this change does it fix the compiler error.
- [x ] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)
> Fix compilation on MacOS

- src/types/float_type.rs
- tests/all/test_values.rs
Marks the const_float_from_string method as unsafe and adds an assertion that the string isn't empty
#513 
Locally w/ LLVM 17
The method is now unsafe, an assertion triggers on empty string rather than UB.
> Marked const_float_from_string as unsafe. Fixes #513

- src/module.rs
Fix a memory leak in the `verify` function that calls the `LLVMVerifyModule` function of LLVM.
If we build `inkwell` with Address sanitizer enabled:
`RUSTFLAGS="-Z sanitizer=address" cargo +nightly build --target aarch64-unknown-linux-gnu -Zbuild-std`
And try to use the [the `inkwell::module::Module::verify` function](https://github.com/TheDan64/inkwell/blob/master/src/module.rs#L731-L744), then sanitizer will report the following memory leak (if the function succeeds):
```
==31844==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 2 byte(s) in 2 object(s) allocated from:
#0 0x56420a9edfda in strdup /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:570:3
#1 0x564210600990 in LLVMVerifyModule /__w/era-compiler-tester/era-compiler-tester/target-llvm/build-final …
```
> Fix memory leak caused by LLVMVerifyModule function call

- src/context.rs
This makes some functions in Context and ContextRef `pub` instead of `pub(crate)`. 
Also adds getter for raw LLVMContextRef
Tested with llvm18-0 in my code that uses `melior`, `mlir-sys` and `inkwell` together.
> expose functions for working with LLVMContextRef for interoperability with other libraries

- src/module.rs
- tests/all/test_module.rs
Change the function `Module::write_bitcode_to_path` to accept a `AsRef<Path>` argument instead of `&Path`. This allows passing e.g. string slices instead of explicitly building the `Path` instance, and matches functions in `std::fs`.
Since `&Path` is `AsRef<Path>`, the change is backwards compatible.
- Adapted the example in the docstring
- The tests checks passing an explicit `Path`.
> module: make write_bitcode_to_path accept more general path representations

- src/builder.rs
- src/values/call_site_value.rs
- src/values/mod.rs
- src/values/operand_bundle.rs
- tests/all/test_values.rs
Implement a safe API wrapping the [operand bundles](https://llvm.org/docs/LangRef.html#operand-bundles) manipulation calls in `llvm-sys`. The feature requires llvm18+.
Building `call` instructions is done with the new `Builder::build_direct_call_with_operand_bundles`  and `Builder::build_indirect_call_with_operand_bundles`.
Since only `call` and `invoke` instructions support operand bundles, introspection methods are implemented on `CallSiteValue`. `CallSiteValue::get_operand_bundles()` produces an iterator of `OperandBundle` values, and `OperandBundle::get_args()` iterates over a bundle's arguments. `OperandBundle::tag()` retrieves the bundle's tag as a string slice.
Resolves #523
Ran tests for LLVM 16 and 18.
> Implement safe API for operand bundles.

- src/builder.rs
creates a wrapper for `LLVMBuildBinOp`
https://github.com/TheDan64/inkwell/issues/538
Locally with llvm18, it should exist in all llvm versions
> wrapper for LLVMBuildBinOp

- Cargo.toml
The new versions contain fixes for building against the musl target.
> bump llvm-sys

- src/builder.rs
- src/types/enums.rs
- src/types/float_type.rs
- src/types/int_type.rs
- src/types/mod.rs
- src/types/ptr_type.rs
- src/types/scalable_vec_type.rs
- src/types/traits.rs
- src/values/enums.rs
- src/values/mod.rs
- src/values/scalable_vec_value.rs
- src/values/traits.rs
- tests/all/test_builder.rs
- tests/all/test_instruction_values.rs
- tests/all/test_types.rs
- tests/all/test_values.rs
This adds scalable vector support through the new `ScalableVectorType` and `ScalableVectorValue`.
#541 
Tests mirroring the fixed vector kind have been added for type, value and builder.
> Add scalable vector

- src/builder.rs
Resets the `positioned` field in the `Builder::clear_insertion_position` method. This fixes the problem described in https://github.com/TheDan64/inkwell/issues/560.
Fixes https://github.com/TheDan64/inkwell/issues/560.
```
$ cargo test -q -F llvm18-0 2>/dev/null
running 3 tests
...
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
running 150 tests
...................................................................i................... 87/150
...............................................................
test result: ok. 149 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.02s
running 344 tests
....................................................................................... 87/344 …
```
> Reset `positioned` in `Builder::clear_insertion_position`

- src/lib.rs
- src/memory_manager.rs
- src/module.rs
- tests/all/test_execution_engine.rs
---
This PR adds a new function, `create_mcjit_execution_engine_with_memory_manager`, which allows users to supply their own JIT memory manager (`McjitMemoryManager` trait). This enables custom allocation, finalization, and teardown logic for code and data sections under MCJIT.
Close #296
Tested on a Mac M1 MAX host running Docker (Debian bookworm),  
with LLVM 18 installed inside the container.
- Manually and testcode verified on AArch64 Linux with a small JIT-compiled function.
```
f64 test_fn() {
entry:
call void @llvm.experimental.stackmap(i64 12345, i32 0)
ret f64 64.0
}
```
- Confirmed that user-defined `allocate_code_section`, `allocate_data_section`, `finalize_memory`, and `destroy` callbacks are invoked by MCJIT.
- No regressions observed in existing tests (the standard test …
> Add create_mcjit_execution_engine_with_memory_manager for custom MCJIT memory management

- src/builder.rs
- src/debug_info.rs
- src/lib.rs
- src/memory_manager.rs
- src/module.rs
- src/passes.rs
- src/types/enums.rs
- src/values/instruction_value.rs
- tests/all/test_values.rs
Fix warnings reported by `rustdoc` and `typos` invocations.
No code change except for 2c6427dcb640589e135d1ae404a90134f90b41b1.
When building the documentation with LLVM > 16, there's a broken link to `add_prune_eh_pass` in `builder.rs` (`build_invoke`) because the function doesn't exist. Linked to #505.
> docs: fix warnings and typos

- src/types/enums.rs
- src/types/fn_type.rs
- tests/all/test_types.rs
Fixes #546 as suggested in the issue.
`FunctionType::get_param_types()` now returns `Vec<BasicMetadataTypeEnum>` instead of `Vec<BasicTypeEnum>`.
The conversion is provided by implementing `BasicMetadataTypeEnum::new`, which delegates to `BasicTypeEnum::new` for non-metadata types. This only works for LLVM >= 6, because of the same gate on `MetadataType::new`.
#546
- dedicated non-regression test for the original issue.
- enabled running the doctest on `FunctionType::get_param_types()`.
Signature change for `FunctionType::get_param_types()`.
> FunctionType::get_param_types: support metadata type

- src/values/call_site_value.rs
- src/values/fn_value.rs
- tests/all/test_attributes.rs
- tests/all/test_values.rs
Fixes #571.
- `CallSiteValue::get_called_fn_value` now matches the behavior of [`CallBase::getCalledFunction`](https://llvm.org/doxygen/classllvm_1_1CallBase.html#a2b1ae7cf1bafdd43d1fee4c6ad0a2913) and returns `None` when the underlying instruction is an indirect call or a type inconsistency is detected (the latter only for LLVM >= 8).
- The new `CallSiteValue::get_called_fn_type` corresponds to [`CallBase::getFunctionType`](https://llvm.org/doxygen/classllvm_1_1CallBase.html#ac3c35bd078a268a207f607d0f57dadba) and returns the type of the function called by the underlying call/invoke instruction. This is always well defined, whether the call is indirect or not. This new function only exists for LLVM >=8 because it depends on `LLVMGetCalledFunctionType`.
#571 
Non-regression on #571 is …
> CallSiteValue::get_called_fn_value: return None on indirect calls

- src/values/enums.rs
Currently, when an `into` conversion fails, the error location reported points to the source code of Inkwell, e.g.
```
thread 'main' panicked at /home/rakivo/Coding/inkwell/src/values/enums.rs:369:13:
```
This can be quite frustrating because, to determine where your program failed to perform the conversion, you either need to run it with `RUST_BACKTRACE=1` and then examine the stack trace or use a debugger.
> Report user's call location in case of `panic` in `into_*_value` type of functions

- src/types/float_type.rs
- tests/all/test_types.rs
This adds the `get_bit_width` function to float type similar to the one found in integer type.
#437 
Added new unit test
> Add `get_bit_width` method for float type

- src/builder.rs
The is_alignment_ok function in builder.rs uses log2 to determine the number of bits that are number needs. It compares the result with `64`. This is unnecessary as the `align` parameter is only 32-bits, so this comparison will always return `true`.
If `align` were 64-bit, the check would still be unnecessary because you can't have 2^64 as a 64-bit value. If `align` were 128-bit, then you could perform this check using `align.trailing_zeros()`, which is faster than converting to f64 and using log2, which would be inaccurate for an 128-bit integer anyway.
No tests needed. It's logically sound.
- [x ] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)
> Removes uneccesary less-than 64-bit check on 32-bit value.
